import { useState, useEffect } from 'react';
import { Bug } from 'lucide-react';
import { BugReportModal } from './BugReportModal';
import { RouteTracker } from './RouteTracker';
import { cn } from '@/lib/utils';
import { SYSTEM_NAME, BUG_REPORTER_API_URL } from './config';
import type { BugReporterConfig } from './types';

/**
 * BugReporter — Drop-in floating bug reporter for any ViacoreMedia project.
 * 
 * Config is read from ./config.ts (generated by the setup CLI).
 * Props can override config values if needed.
 */
export function BugReporter({ systemName, apiUrl, user, contact }: Partial<BugReporterConfig> = {}) {
  const name = systemName || SYSTEM_NAME;
  const baseUrl = apiUrl || BUG_REPORTER_API_URL;
  const [isOpen, setIsOpen] = useState(false);

  // Auto-register system on first load
  useEffect(() => {
    const storageKey = `bug-reporter-${name}-registered`;
    
    if (localStorage.getItem(storageKey)) return;
    
    fetch(`${baseUrl}/api/bugs/register`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ 
        systemName: name,
        contact: contact || 'joshua@viacoremedia.com' 
      }),
    })
      .then(res => res.json())
      .then(() => {
        localStorage.setItem(storageKey, 'true');
      })
      .catch(() => {
        // Silent fail - will retry on next page load
      });
  }, [name, baseUrl, contact]);

  return (
    <>
      {/* Console log interceptor — starts buffering immediately */}
      <RouteTracker />

      {/* Floating Button */}
      <button
        onClick={() => setIsOpen(true)}
        className={cn(
          "fixed bottom-6 right-6 z-[9997]",
          "w-10 h-10 rounded-full",
          "bg-muted/80 hover:bg-muted",
          "border border-border shadow-lg",
          "flex items-center justify-center",
          "transition-all duration-200",
          "hover:scale-110 hover:shadow-xl",
          "group"
        )}
        title="Report a Bug"
        aria-label="Report a Bug"
      >
        <Bug className="h-4 w-4 text-muted-foreground group-hover:text-foreground transition-colors" />
      </button>

      {/* Modal */}
      <BugReportModal
        isOpen={isOpen}
        onClose={() => setIsOpen(false)}
        systemName={name}
        apiUrl={baseUrl}
        user={user}
      />
    </>
  );
}
