// ============================================
// BUG REPORTER CONFIGURATION
// This file is auto-generated by the setup CLI.
// Override values here or pass props to <BugReporter />.
// ============================================

export const SYSTEM_NAME = "Unknown System";
export const BUG_REPORTER_API_URL = "https://bug-reporter-tau.vercel.app";
